---
name: 'CloudTruth Configure'
description: 'Securely deliver CloudTruth configuration and secrets into your GitHub Actions workflows.'
author: 'CloudTruth, Inc.'
inputs:
  token:
    description: 'The CloudTruth service account token to use - this defines the Organization.'
    required: true
  project:
    description: 'The CloudTruth project name within the organization.'
    required: true
  environment:
    description: 'The CloudTruth environment lens to apply to the project.'
    required: true
  overwrite:
    description: 'Allow environment variables to be overwritten.'
    default: false
  server:
    description: 'The CloudTruth server to execute the query against.'
    default: 'api.cloudtruth.com'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'settings'
  color: 'blue'
