---
name: 'CloudTruth Configure'
description: 'Securely deliver CloudTruth configuration and secrets into your GitHub Actions workflows.'
author: 'CloudTruth, Inc.'
inputs:
  apikey:
    description: 'The CloudTruth Service Account API key to use.'
    required: true
  project:
    description: 'The CloudTruth project (name or id) within the organization.'
    required: true
  environment:
    description: 'The CloudTruth environment (name or id) to view the project through.'
    required: true
  tag:
    description: 'The environment tag name to use.  If not specified, current values are retrieved.'
    required: false
  overwrite:
    description: 'Allow environment variables to be overwritten.'
    default: 'false'
    required: false
  server:
    description: 'The CloudTruth server to execute the query against.'
    default: 'https://api.cloudtruth.io'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'settings'
  color: 'blue'
